### ISSUE TITLE
no data points are shown in the map if any column contains a empty value

### ISSUE THREAD

**Issue by modularTaco** [orchestracities/grafana-map-plugin#39]
Hey,

since the latest commits the panel won't show any points in the map anymore if some column contains empty (not NULL) values.

E.g.
```
SELECT name AS id, location AS geojson, time_index as created_at, foo, bar, 'none' as type
FROM foo.bar
```

With foo.bar as
| name | location | time_index | foo | bar |
| --- | --- | --- | --- | --- |
| `"name1"` | valid geojson | valid timestamp | `"value"` | `"value`" |
| `"name2"` | valid geojson | valid timestamp | `""` | `"value"` |

-> The map is empty. No points are drawn, no error is logged to the console or shown in the UI. Grafana query inspector looks good, query works as expected.

Env where this worked as expected: 
Grafana: 7.0.6
Map Plugin commit sha: f19381d

Env where it does not work anymore:
Grafana: 7.4.0
Map plugin commit sha: 317b0be

Workaround:
```
SELECT name AS id, location AS geojson, time_index as created_at,
CASE
    WHEN foo = '' THEN 'EMPTY'
    ELSE foo
END AS foo,
bar, 'none' as type
FROM foo.bar
```

**Comment by chicco785** [comment]
thx, it seems to us that this related to the grafana version, plugin as by docker-compose was tested to support 7.3.7, not with 7.4.x

**Comment by modularTaco** [comment]
> thx, it seems to us that this related to the grafana version, plugin as by docker-compose was tested to support 7.3.7, not with 7.4.x

thanks for the quick reply!

OK I'll check again with 7.3.7 on monday

**Comment by modularTaco** [comment]
> thx, it seems to us that this related to the grafana version, plugin as by docker-compose was tested to support 7.3.7, not with 7.4.x

The error is also present with grafana 7.3.7, but different.  
In 7.4.0 there was no error message, only a map without points.  
in 7.3.7 i get the following error messages and no map is shown at all.  

console errors:
```
vendors~app.ddf7518003180e1ca7bc.js:2 TypeError: filteredData[dpKey].toFixed is not a function
    at eval (map_utils.js:79)
    at Array.map (<anonymous>)
    at translate (map_utils.js:78)
    at getDataPointStickyInfo (map_utils.js:36)
    at WorldMap.createIcon (worldmap.js:294)
    at eval (worldmap.js:211)
    at Array.forEach (<anonymous>)
    at eval (worldmap.js:185)
    at Array.forEach (<anonymous>)
    at WorldMap.drawPoints (worldmap.js:116)
```
```
leaflet.js:5 Uncaught TypeError: Cannot read property '_leaflet_pos' of undefined
    at Li (leaflet.js:5)
    at i._getMapPanePos (leaflet.js:5)
    at i._rawPanBy (leaflet.js:5)
    at invalidateSize (leaflet.js:5)
    at eval (worldmap.js:447)
```

grafana UI error:
```
An unexpected error happened
DetailsTypeError: filteredData[dpKey].toFixed is not a function

    in t
    in Cn
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in oi
    in div
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

**Comment by chicco785** [comment]
@modularTaco having several issues with version 7+ and angular, we have been working in the last months, to rewrite the plugin to use react, we are almost there, be patient!

**Comment by chicco785** [comment]
if you are interested in a preview: https://github.com/orchestracities/grafana-map-plugin/tree/migration-to-8.0.0-timescale-support-test

happy if you can test and spot bugs, non functioning aspects based on your data

**Comment by chicco785** [comment]
@modularTaco the new release is available here:
https://github.com/orchestracities/grafana-map-plugin/releases/tag/v1.4.0

haven't tested the specific issue, in case it still occurs, please open a new ticket.
thanks a stack!
