### ISSUE TITLE
How to display (multi)polygons? 

### ISSUE THREAD

**Issue by ChrizZz90** [orchestracities/grafana-map-plugin#40]
Hey guys, @amotl made me aware of your plugin.

I have a PostGIS database with polygon data based on postal codes. I want to display them together with additional data of my Postgres database. 

At first I made a query based on PostGIS geometry data. After that I tried to convert the geometry data into GeoJSON and finally my 3rd try was to convert the whole query into json with the additional data as properties. But in every case the polygons weren't displayed. Is there any documentation or code snippets you can share with me to help me get that running?

**Comment by chicco785** [comment]
@ChrizZz90 sorry, we missed your issue, actually we haven't tested so far the plugin with postgis (we did with cratedb), probably you would need to change some part of the code. We are working now on the porting to 8.0.0, basically rewriting it from scratch. While doing that, we can also test postgis.

**Comment by chicco785** [comment]
so, in the new version, it's quite straight forward, you need to use the proper query on the geometry field to extract the geojson. you can have a look here: https://github.com/orchestracities/grafana-map-plugin/tree/migration-to-8.0.0-timescale-support-test

**Comment by chicco785** [comment]
here is the documentation for postgis:
https://github.com/orchestracities/grafana-map-plugin#usage-with-postgis
