### ISSUE TITLE
geoJson polygons: Color not changing with change in timerange

### ISSUE THREAD

**Issue by edalevol** [orchestracities/grafana-map-plugin#54]
Hello, and thank you for making this awsome plugin. I have been in the need of a map panel that can draw polygons and color them by data for a while now and stumbled upon this one yesterday. 

The issue is that the color of polygons doesn't change when i change the timerange (and in return the "color by" attribute). The attributes of the polygons does change and is correctly shown when hovering over a feature, but in order to redraw the polygons with the correct color from the new data i need to do a full page refresh. 

This seems to only be an issue with the polygon type from geoJson. (and maybe linestring type, haven't testet that). 
When i use either points from lat/lon or type point from geoJson, the points are re-rendered with new colors on change in timerange as expected. 

Tested with:
Grafana 8.3.0
Postgres13 (with postgis and timescale extensions)
Browser: Chrome

Best regards, 

Eivind

**Comment by chicco785** [comment]
@edalevol i think this relates to style caching, ideally this reduce computation... but apparently it does no work as planned :/

**Comment by chicco785** [comment]
v1.4.1 should solve the issue, reducing a bit performance .

**Comment by edalevol** [comment]
Awsome, thank you for the quick fix! I tested the new version and I can confirm it works now. :)

**Comment by chicco785** [comment]
you are welcome. should you have other features / bugs feel free to fill in. may take longer :) we have been quick on this since it was affecting customers.
